#!/usr/bin/env python3
"""Canonical two-toolchain Product run of the imported WP-08 R52 package.

Generates the adapter's vector header from the package's evidence/plan.json,
compiles the engine sources plus wp08p_adapter.c under real GCC and real Clang
with the package's own flags, runs both, requires the two complete streams to
be byte-identical, retains them, and applies the package's own
oracle.parse_jsonl to the stream. Nothing here decides a verdict; the oracle
does, and its outcome is this script's exit status.

  --evidence DIR   fresh output directory (refuses to reuse one)
  --retained DIR   also require the fresh streams to equal the committed evidence
  --replay DIR     offline: verify committed evidence and apply the oracle
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
PACKAGE = ROOT / "tests" / "portability_wp08_r52"
PLAN = PACKAGE / "evidence" / "plan.json"
ADAPTER_SRC = HERE / "wp08p_adapter.c"

VERIFIER_TREE = "d1ba52f7a756ee982cdcf03e0369a2b91bc44301"
VERIFIER_SOURCE = "3dbd22520f0c9d30da38d60fe883c7b4f8e9fbe7"
PRODUCT_BASE = "39d2076fa204991ec9c0d43f00b502942556bf9a"
IMPORT_COMMIT = "1dd1c8e"
PLAN_FILE_SHA256 = "7b8b133629bc833025d32e42f34f757e14d10e5f18abecf09de4b9d705b682e6"

sys.path.insert(0, str(PACKAGE))
from toolchains import FLAGS  # noqa: E402  package flags, not a verdict


def git(*args: str) -> str:
    return subprocess.run(["git", "-C", str(ROOT), *args], check=True,
                          capture_output=True, text=True).stdout.strip()


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha(path.read_bytes())


def check_provenance() -> None:
    if git("rev-parse", "HEAD:tests/portability_wp08_r52") != VERIFIER_TREE:
        raise SystemExit("verifier tree at HEAD is not " + VERIFIER_TREE)
    imp = git("rev-parse", IMPORT_COMMIT)
    if git("rev-parse", imp + "^") != PRODUCT_BASE:
        raise SystemExit(f"import {imp} parent is not the declared base {PRODUCT_BASE}")
    if git("rev-parse", imp + ":tests/portability_wp08_r52") != VERIFIER_TREE:
        raise SystemExit(f"import {imp} does not carry tree {VERIFIER_TREE}")
    if subprocess.run(["git", "-C", str(ROOT), "merge-base", "--is-ancestor", imp, "HEAD"]).returncode:
        raise SystemExit(f"import {imp} is not an ancestor of HEAD")
    if sha256_file(PLAN) != PLAN_FILE_SHA256:
        raise SystemExit("plan.json is not the published plan")


def header_text() -> str:
    """The adapter's input: each plan row verbatim, plus its fixture identity as
    the package defines it (SHA-256 of the row's canonical JSON)."""
    rows = json.loads(PLAN.read_text())
    lines = ["/* generated by run_product.py from tests/portability_wp08_r52/evidence/plan.json */",
             f"#define VECTOR_COUNT {len(rows)}",
             "static const struct vector VECTORS[VECTOR_COUNT] = {"]
    for r in rows:
        fixture = sha(json.dumps(r, sort_keys=True, separators=(",", ":")).encode())
        pcm = ", ".join("{%d, %d}" % tuple(f) for f in r["frames"]) or "{0, 0}"
        runs = ", ".join(str(x) for x in r["runs"]) or "0"
        lines += ["  {", f'    .id = "{r["id"]}",', f'    .fixture_sha256 = "{fixture}",',
                  f'    .frame_count = {len(r["frames"])}u,', f"    .pcm = {{{pcm}}},",
                  f'    .run_count = {len(r["runs"])}u, .runs = {{{runs}}},',
                  f'    .seek = {r["seek"]}ull, .rate = {r["rate"]}, .requested = {r["requested"]}u',
                  "  },"]
    return "\n".join(lines + ["};", ""])


def compiler(name: str, family: str) -> tuple[str, str]:
    path = shutil.which(name)
    if not path:
        raise SystemExit(f"required {family} compiler unavailable: {name}")
    identity = subprocess.run([path, "--version"], check=True, capture_output=True,
                              text=True).stdout.splitlines()[0]
    if family not in identity.lower():
        raise SystemExit(f"{name} did not identify as {family}: {identity}")
    return path, identity


def build_and_run(gcc: str, clang: str) -> tuple[dict, dict, str]:
    sources = sorted(str(p) for p in (ROOT / "engine" / "src").glob("*.c"))
    streams, meta = {}, {}
    text = header_text()
    with tempfile.TemporaryDirectory(prefix="wp08p-") as tmp:
        tmp = Path(tmp)
        (tmp / "plan_vectors.h").write_text(text, newline="\n")
        for family, name in (("gcc", gcc), ("clang", clang)):
            path, identity = compiler(name, family)
            exe = tmp / (family + (".exe" if os.name == "nt" else ""))
            cmd = [path, *FLAGS, "-I", str(tmp), "-I", str(ROOT / "engine" / "include"),
                   *sources, str(ADAPTER_SRC), "-o", str(exe)]
            subprocess.run(cmd, check=True)
            stream = tmp / f"{family}.jsonl"
            subprocess.run([str(exe), str(stream)], check=True)
            streams[family] = stream.read_bytes()
            meta[family] = {"identity": identity, "flags": list(FLAGS)}
    return streams, meta, sha(text.encode())


def canonical_verdict(stream: bytes) -> int:
    import oracle  # the package's own; decides
    try:
        oracle.parse_jsonl(stream)
    except AssertionError as e:
        print(f"oracle.parse_jsonl: FAIL: {e}")
        return 1
    print("oracle.parse_jsonl: PASS 41 vectors")
    return 0


def fresh_dir(path: Path) -> Path:
    path = path if path.is_absolute() else ROOT / path
    if path.exists() and any(path.iterdir()):
        raise SystemExit(f"refusing to reuse non-empty evidence directory {path}")
    path.mkdir(parents=True, exist_ok=True)
    return path


def read_sums(d: Path) -> dict:
    out = {}
    for line in (d / "SHA256SUMS").read_text().splitlines():
        digest, name = line.split(None, 1)
        out[name.lstrip("*")] = digest
    return out


def load_retained(d: Path) -> dict:
    sums = read_sums(d)
    for name in ("gcc.jsonl.gz", "clang.jsonl.gz", "manifest.json"):
        if sha256_file(d / name) != sums[name]:
            raise SystemExit(f"retained {name} does not match its committed SHA-256")
    streams = {f: gzip.decompress((d / f"{f}.jsonl.gz").read_bytes()) for f in ("gcc", "clang")}
    manifest = json.loads((d / "manifest.json").read_text())
    for f in ("gcc", "clang"):
        if sha(streams[f]) != manifest["observations_sha256"]:
            raise SystemExit(f"retained {f} stream does not match the manifest")
    return streams


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--evidence", type=Path)
    g.add_argument("--replay", type=Path)
    ap.add_argument("--retained", type=Path)
    ap.add_argument("--gcc", default="gcc")
    ap.add_argument("--clang", default="clang")
    a = ap.parse_args()

    check_provenance()

    if a.replay:
        d = a.replay if a.replay.is_absolute() else ROOT / a.replay
        streams = load_retained(d)
        if streams["gcc"] != streams["clang"]:
            raise SystemExit("retained GCC and Clang streams differ")
        print(f"retained streams byte-identical, {sha(streams['gcc'])}")
        return canonical_verdict(streams["gcc"])

    out = fresh_dir(a.evidence)
    head = git("rev-parse", "HEAD")
    product_commit = os.environ.get("PRODUCT_COMMIT") or head
    streams, meta, header_sha = build_and_run(a.gcc, a.clang)
    identical = streams["gcc"] == streams["clang"]
    print(f"GCC and Clang streams byte-identical: {identical}")
    if not identical:
        for f in ("gcc", "clang"):
            (out / f"{f}.jsonl").write_bytes(streams[f])
        raise SystemExit("cross-toolchain Product streams diverged; both retained unpacked for inspection")

    for f in ("gcc", "clang"):
        (out / f"{f}.jsonl.gz").write_bytes(gzip.compress(streams[f], compresslevel=9, mtime=0))
    manifest = {
        "schema": "wp08-portability-r52-product-manifest-1",
        "scope": "Product observations; the package oracle decides; not acceptance",
        "verifier_tree": VERIFIER_TREE,
        "verifier_source_commit": VERIFIER_SOURCE,
        "product_base": PRODUCT_BASE,
        "import_commit": git("rev-parse", IMPORT_COMMIT),
        "engine_tree": git("rev-parse", "HEAD:engine"),
        "adapter_source_sha256": sha256_file(ADAPTER_SRC),
        "run_product_sha256": sha256_file(Path(__file__)),
        "generated_header_sha256": header_sha,
        "plan_file_sha256": PLAN_FILE_SHA256,
        "case_count": len(json.loads(PLAN.read_text())),
        "byte_identical_observations": True,
        "observations_sha256": sha(streams["gcc"]),
        "gcc": meta["gcc"],
        "clang": meta["clang"],
        "build": "each compiler builds engine/src/*.c and wp08p_adapter.c together with the package FLAGS",
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", newline="\n")
    names = ("gcc.jsonl.gz", "clang.jsonl.gz", "manifest.json")
    (out / "SHA256SUMS").write_text("".join(f"{sha256_file(out / n)}  {n}\n" for n in names), newline="\n")
    (out / "host.json").write_text(json.dumps({"product_commit": product_commit, "head": head,
                                               "product_tree": git("rev-parse", product_commit + "^{tree}")},
                                              indent=2, sort_keys=True) + "\n", newline="\n")

    if a.retained:
        d = a.retained if a.retained.is_absolute() else ROOT / a.retained
        if load_retained(d)["gcc"] != streams["gcc"]:
            raise SystemExit("regenerated streams differ from the committed retained evidence")
        print("regenerated streams are byte-identical to the retained evidence")

    return canonical_verdict(streams["gcc"])


if __name__ == "__main__":
    raise SystemExit(main())
