#!/usr/bin/env python3
"""Make the >3-day held-stream escalation actually fire.

CLAUDE.md §4 requires escalation to PM when a stream is held more than three
days. The engine stream has been held since 11 September and nothing fired,
because nothing was checking. A rule nobody checks is not a rule.

Held detection is deliberately TWO-WAY:

  * the `held` label, which is the convention WO-7 introduces; and
  * a title matching HELD / (HELD, ... ), which is the convention this
    repository has actually used since PR #20 on 3 September.

Keying on the label alone would have produced a gate that never fires -- at the
time of writing not one open PR carried that label, while six were held by
title and by STATUS. A gate that never goes red has not established what it
detects (CLAUDE.md §1).

Comments at most once per over-age held PR per seven days, deduplicated on a
hidden marker. Escalation is a notification; it accepts nothing, dispositions
nothing and advances no rung.

Usage:
  stream-age.py --dry-run      print what it would post, post nothing
  stream-age.py                post
Environment: GITHUB_TOKEN, GITHUB_REPOSITORY (owner/repo).
"""
import argparse
import datetime as dt
import json
import os
import re
import sys
import urllib.error
import urllib.request

API = "https://api.github.com"
MARKER = "<!-- stream-age-escalation -->"
HELD_DAYS = 3
REPEAT_DAYS = 7
HELD_TITLE = re.compile(r"(^|\W)HELD(\W|$)", re.I)


def gh(path, token, method="GET", body=None):
    req = urllib.request.Request(f"{API}{path}", method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github+json")
    data = None
    if body is not None:
        data = json.dumps(body).encode()
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, data) as r:
        return json.loads(r.read() or "null")


def parse_ts(s):
    return dt.datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=dt.timezone.utc)


def held_since(pr, repo, token):
    """When this PR became held, and how we know."""
    labels = [l["name"] for l in pr.get("labels", [])]
    if "held" in labels:
        try:
            events = gh(f"/repos/{repo}/issues/{pr['number']}/events?per_page=100", token)
            stamps = [parse_ts(e["created_at"]) for e in events
                      if e.get("event") == "labeled" and e.get("label", {}).get("name") == "held"]
            if stamps:
                return min(stamps), "held label"
        except urllib.error.HTTPError:
            pass
        return parse_ts(pr["created_at"]), "held label (label event unavailable)"
    if HELD_TITLE.search(pr["title"] or ""):
        return parse_ts(pr["created_at"]), "HELD in title"
    return None, None


def already_commented(repo, number, token, now):
    try:
        comments = gh(f"/repos/{repo}/issues/{number}/comments?per_page=100", token)
    except urllib.error.HTTPError:
        return False
    for c in comments:
        if MARKER in (c.get("body") or ""):
            if (now - parse_ts(c["created_at"])).days < REPEAT_DAYS:
                return True
    return False


def body(pr, since, how, age):
    return f"""{MARKER}
### Held stream escalation — {age} days

`CLAUDE.md` §4 requires escalation to PM when a stream is held more than
{HELD_DAYS} days. This PR has been held since **{since:%Y-%m-%d}** ({age} days), detected
by **{how}**.

| | |
|---|---|
| PR | #{pr['number']} — {pr['title']} |
| Held since | {since:%Y-%m-%d} ({age} days) |
| Detected by | {how} |
| Charter requirement | Escalate to PM via an issue labeled `pm` |

**What the charter asks for:** open or update a `pm`-labeled issue carrying the
evidence, a recommendation and a safe default. No default overrides a structural or
safety hold.

This comment is a notification produced by `.github/workflows/stream-age.yml`. It
**accepts nothing, dispositions nothing and advances no rung**, and it does not
mean the hold is wrong — a long hold may be exactly correct. It means the charter's
own escalation step has not visibly happened.

Repeats at most once every {REPEAT_DAYS} days while the hold stands. Closing or
un-holding the PR stops it.

---
_Generated by [Claude Code](https://claude.ai/code)_"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", ""))
    a = ap.parse_args()
    token = os.environ.get("GITHUB_TOKEN", "")
    if not (token and a.repo):
        print("need GITHUB_TOKEN and --repo/GITHUB_REPOSITORY", file=sys.stderr)
        return 2

    now = dt.datetime.now(dt.timezone.utc)
    prs = gh(f"/repos/{a.repo}/pulls?state=open&per_page=100", token)
    print(f"== held stream age == {len(prs)} open PRs, threshold {HELD_DAYS} days")
    posted = 0
    for pr in sorted(prs, key=lambda p: p["number"]):
        since, how = held_since(pr, a.repo, token)
        if since is None:
            continue
        age = (now - since).days
        tag = f"#{pr['number']:<4} held {age:>3}d via {how:<28}"
        if age <= HELD_DAYS:
            print(f"  ok    {tag} within threshold")
            continue
        if already_commented(a.repo, pr["number"], token, now):
            print(f"  skip  {tag} already escalated within {REPEAT_DAYS} days")
            continue
        if a.dry_run:
            print(f"  WOULD {tag} POST escalation")
        else:
            gh(f"/repos/{a.repo}/issues/{pr['number']}/comments", token, "POST",
               {"body": body(pr, since, how, age)})
            print(f"  post  {tag} escalation posted")
        posted += 1
    print(f"== {posted} escalation(s) {'that would be ' if a.dry_run else ''}posted ==")
    return 0


if __name__ == "__main__":
    sys.exit(main())
